### ISSUE TITLE
Website isn't working

### ISSUE THREAD

**Issue by ammarasmro** [jadianes/spark-py-notebooks#12]
Thanks for the tutorials!
The domain of the website is probably expired and the .github.io link is routing to that domain too. 

Possible solutions: 

1. Renew the domain subscription
2. Cancel the alias or record that's causing the GitHub page to go to the custom domain

**Comment by jadianes** [comment]
Sorted. Thanks!

**Comment by jadianes** [comment]
Sorted. Thanks!
