### ISSUE TITLE
spark context

### ISSUE THREAD

**Issue by PChiberre** [jadianes/spark-py-notebooks#4]
I had an issue with the command line 
$ MASTER="spark://127.0.0.1:7077" SPARK_EXECUTOR_MEMORY="1G" IPYTHON_OPTS="notebook --pylab inline" /home/philippe/Downloads/spark-master/bin/pyspark

the error was Connection refused: /127.0.0.1:7077

and was resolved with 
$ MASTER=local[4] SPARK_EXECUTOR_MEMORY="1G" IPYTHON_OPTS="notebook --pylab inline" /home/philippe/Downloads/spark-master/bin/pyspark
maybe you could say a word in the readme about it.

Otherwise great notebooks and great help Thank you!

**Comment by jadianes** [comment]
Sure. I'm using an actual cluster. I guess you're using a local installation. Well done!
